### PR TITLE
Adding the ability to send a list of ICE servers to the SDP request so WebRTC can be used over WAN.

### PR DESCRIPTION
**Pull request by QuinnDamerell**
This change allows clients to optionally send a list of ICE servers as part of the HTTP SDP request POST, which is used for the created peer connection. This will enable clients to use internet STUN and TURN servers and the local ICE candidates, thus allowing WAN-based WebRTC connections. If no ICE servers are sent, the existing logic remains the same, only offering a local ICE candidate.

Context: I'm the developer behind OctoEverywhere.com, a free remote access service used by the OctoPrint and Klipper communities. My project allows users full and secure access to their web portals, including webcam streaming. With the old mjpeg stream, I have my service set up to proxy the stream, but WebRTC has new challenges.  

Both OctoPrint and Moonraker have recently adopted camera-streamer (which is fantastic 🤩), and I want to be able to support WebRTC over the WAN as well. I'm still exploring how to do it, but at a minimum, I need to be able to configure the WebRTC client to use STUN and possibly TURN servers for the connection so it attempts to connect over the WAN and the LAN.

I'm very open to feedback and excited to hear what you think!

### CODE REVIEW

**Comment by QuinnDamerell** [comment]
@ayufan great! I appreciate it! The only thing I wanted to work out is that when setting ICE servers, the WebRTC lib seems to not auto-include the local ICE candidate. I will check the libdatachannel logic to see if I can keep that included; it's handy to have so users always connect locally if possible. 

I'm also trying to get this change made ASAP, as OctoPrint and Moonraker are moving to camera-streamer right now, and as far as I know, once installed neither have a good update path for it.

**Comment by ayufan** [comment]
@QuinnDamerell The OctoPi is upgradeable. `crowsnest` I believe is not without user intervention.

**Comment by QuinnDamerell** [comment]
@ayufan I know that Octopi has that cool auto image creator, but I think on the image is made, there's no update path. So that means anyone who uses an old image is stuck on whatever version they got, as far as I know.

**Comment by ayufan** [comment]
@QuinnDamerell I made this change very similar to yours: https://github.com/ayufan/camera-streamer/commit/99c8415f02fe3a33a3d52a53dab6eeede4838e32. You can check this in `develop` branch.

**Comment by QuinnDamerell** [comment]
@ayufan thanks! Jw, is it disabled by default, or am I reading this wrong?

`DEFINE_OPTION_DEFAULT(webrtc, disable_client_ice, bool, "1", "Ignore ICE servers provided in '/webrtc' request."),`

Is there any reason to disable it? Since the /webrtc calls will exclude the ice servers, it's already an opt-in. It would be great the ice servers would be accepted by default if they are in the request, so I don't have to change any other systems that configure camera-streamer.

**Comment by QuinnDamerell** [comment]
Ah, that totally makes sense, sorry! 

Btw, is there an easy way to dev camera-streamer locally on Linux? Is there some kind of dev flow you follow?

**Comment by QuinnDamerell** [comment]
Sorry for all of the questions, I only have one more. What's your cadence to go into master? I'm just trying to coordinate my work and was wondering if you had some timeline. :)

**Comment by ayufan** [comment]
I think those changes that are currently in develop have some urgency. I
need to confirm that usage of develop will not break crowsnest before merge
to master.

OctoPi uses precompiled packages (which is safer), crowsnest currently
builds from branch which is less ideal.

**Comment by QuinnDamerell** [comment]
Perfect! Yeah, I was going to follow up with the OctoPrint peeps to see if I could get the package updated when it's all ready. I didn't know it was package based for OctoPrint; that's amazing!

Crowsnest / all of Klipper stuff usually targets git repos, which is less than ideal. One thought is that Crowsnest could at least target tagged releases or something, which might make it more stable. But also, as you said, Crowsnest will pull the repo when you run `sudo make install`, but after that, when you update Crowsnest from the Klipper frontends, it only updates the Crowsnest repo, not its compiled libs.

Regardless, thank you so much for your help and being so responsive!

**Comment by ayufan** [comment]
I need to consider, maybe I will push debian repo for camera-streamer.

**Pull request closed without merging**
